name: 99-aws-web-identity
on:
  push:
jobs:
  access_check:
    name: Check AWS Access
    runs-on: ubuntu-latest
    steps:
          - name: Configure AWS credentials
            uses: aws-actions/configure-aws-credentials@v4
            with:
              role-to-assume: arn:aws:iam::588118818861:role/GitHubActionsRole-vinodhdevaarul-ghdevstein
              role-session-name: Github_Devops_Role
              aws-region: us-east-2
